name: Ideas
description: Have a new idea or a feature request, we would love to hear about it.
title: "[FEATURE REQUEST] <description here>"
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature request, idea
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add (multiple) screenshot links (if applicable)
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add any other context about the idea or feature request here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](http://discord.isbathub.org)
        Feel free to check out other cool repositories of the ISBATHub Community [here](https://github.com/ISBATHubCommunity)
